apiVersion: v1
kind: Service
metadata:
  name: redis-second
  labels:
    app: redis-second
spec:
  ports:
  - port: 6380
    name: redisbmaster
  - port: 6379
    name: redisbslave
  selector:
    app: redis-second
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: redis-second
spec:
  serviceName: redis-second
  replicas: 2
  template:
    metadata:
      labels:
        app: redis-second
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: redis-second
        image: rickoliveira1/redis-replicas
        imagePullPolicy: Always
        env:
        - name: SLAVEB
          value: "true"
        - name: PORT
          value: "6380"
        - name: PORTSLAVE
          value: "6379"
        ports:
        - containerPort: 6380
          name: redis-second-master
        - containerPort: 6379
          name: redis-second-slave
